apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foobar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/southworks/myosotis-charts.git
    targetRevision: HEAD
    path: manifest/foobar
  destination:
    server: https://kubernetes.default.svc
    namespace: foobar
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
