argo-cd:
  # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: nginx-eastus
  configs: 
    params: 
      server.insecure: true